version: '3'
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    networks:
      - app-network
    ports:
      - 9000:9000
  mariadb:
    image: 'mariadb:10.6'
    container_name: mariadb
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    tty: true
    links:
      - php:php
      - mariadb:mariadb
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      -  ./public:/srv/app/public
    networks:
      - app-network
volumes:
  dbdata: 
    driver: local
networks:
  app-network:
    driver: bridge 
   